# Manual deployments
name: Manual Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libffi-dev
      run: sudo apt update | sudo apt install libffi-dev
    - name: Install cffi
      run: pip3 install cffi

    - uses: uraimo/run-on-arch-action@v2.0.5
      name: build
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04
        # The shell to run commands with in the container
        shell: /bin/sh
        run: |
          make
          cp liblvgl.so /usr/local/lib | ldconfig
          python3 build.py
          mkdir -p output | mv _* liblvgl.so output

    - uses: actions/checkout@v2
      with:
        ref: build
    - name: Git push commit
      run: |
        git config --global user.name 'github workflow'
        git config --global user.email 'github-workflow@users.noreply.github.com'
        #git checkout build
        git add -f output/*
        git diff --quiet && git diff --staged --quiet || git commit -am 'manual workflow build'
        git push

