# Manual deployments
name: Manual Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04

    - name: Install libffi-dev
      run: sudo apt update | sudo apt install libffi-dev
    - name: Install cffi
      run: pip3 install cffi

    - name: Compile C code
      run: make
    - name: Load LVGL
      run: sudo cp liblvgl.so /usr/local/lib | sudo ldconfig
    - name: Compile build.py
      run: python3 build.py

    - name: Move built files to output folder
      run: mkdir -p output | mv _* liblvgl.so output
    - name: Git add
      run: git add -f output/*
    - name: Git push commit
      run: |
        git config --global user.name 'github workflow'
        git config --global user.email 'github-workflow@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am 'manual workflow build'
        git push

