# Manual deployments
name: Manual Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04
        # The shell to run commands with in the container
        shell: /bin/sh
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)
          apt-get update | apt-get install libffi-dev python3-pip
          pip3 install cffi
          make
          cp liblvgl.so /usr/local/lib | ldconfig
          python3 build.py
          mkdir -p output | mv _* liblvgl.so output
          git add -f output/*
          git config --global user.name 'github workflow'
          git config --global user.email 'github-workflow@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am 'manual workflow build'
          git push

